[pytest]
filterwarnings =
    ignore::UserWarning:torch._inductor
    ignore:'has_cuda' is deprecated:UserWarning:torch
    ignore:'has_cudnn' is deprecated:UserWarning:torch
    ignore:'has_mps' is deprecated:UserWarning:torch
    ignore:'has_mkldnn' is deprecated:UserWarning:torch
