#pragma once

#ifdef ENABLE_PROFILING
    #ifndef NO_CUDA
    #define LUTORCH_MANAGER_ANCHOR_PAIRS_FORWARD_PROFILER_OP 0
    #define LUTORCH_MANAGER_ANCHOR_PAIRS_EVAL_FORWARD_PROFILER_OP 1
    #define LUTORCH_MANAGER_ANCHOR_PAIRS_BACKWARD_PROFILER_OP 2
    #define LUTORCH_MANAGER_LPROJECTION_BACKWARD_PROFILER_OP 3
    #define LUTORCH_MANAGER_LPROJECTION_FORWARD_SMOOTH_PROFILER_OP 4
    #define N_LUTORCH_PROFILER_OPS 5
    #else
    #define N_LUTORCH_PROFILER_OPS 0
    #endif
#endif
