#pragma once

#ifdef ENABLE_PROFILING
#define TORCH_UTILS_DENSE_TO_SPARSE_PROFILER_OP 0
#define TORCH_UTILS_COUNT_NONZERO_PROFILER_OP 1
#define N_TORCH_UTILS_PROFILER_OPS 2
#endif

#define DENSIFY_QUADS_PER_THREAD 16
#define DENSIFY_INTS_PER_THREAD (QUADS_PER_THREAD << 2)
