#pragma once
#include "../connections_manager/connections_manager.h"

#define SYNAPSE_METAS_MEMORY_LABEL N_CONNECTIONS_MANAGER_MEMORY_LABELS
#define NEURON_INFOS_MEMORY_LABEL (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 1)
#define DETECTORS_MEMORY_LABEL (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 2)
#define N_ANDN_MEMORY_LABELS (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 3)

#ifdef ENABLE_PROFILING
#define ANDN_RUNTIME_FIRE_DETECTORS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS
#define ANDN_RUNTIME_FIRE_INPUTS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 1
#define ANDN_RUNTIME_FILL_OUTPUTS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 2
#define ANDN_RUNTIME_CONVERT_OUTPUTS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 3
#define ANDN_RUNTIME_BACKWARD_HEBB_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 4
#define ANDN_RUNTIME_BACKWARD_GRAD_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 5
#define N_ANDN_PROFILER_OPS (N_CONNECTIONS_MANAGER_PROFILER_OPS + 6)
#endif

static_assert(sizeof(EXTERNAL_REAL_DT) == 4, "this andn implementation works only with float32 weights");
