#pragma once
#include "../connections_manager/connections_manager.h"

#define LUT_COMPILE_TIME_KERNELS_TPB 1024
static_assert((LUT_COMPILE_TIME_KERNELS_TPB % 2) == 0, "LUT_COMPILE_TIME_KERNELS_TPB must be even");

#define SYNAPSE_METAS_MEMORY_LABEL N_CONNECTIONS_MANAGER_MEMORY_LABELS
#define NEURON_INFOS_MEMORY_LABEL (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 1)
#define DETECTORS_MEMORY_LABEL (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 2)
#define N_LUT_MEMORY_LABELS (N_CONNECTIONS_MANAGER_MEMORY_LABELS + 3)

#ifdef ENABLE_PROFILING
#define LUT_RUNTIME_FORWARD_NON_SEQ_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS
#define LUT_RUNTIME_FORWARD_NON_SEQ_CHECK_DETECTORS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 1
#define LUT_RUNTIME_FORWARD_NON_SEQ_FILL_OUTPUTS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 2
#define LUT_RUNTIME_FORWARD_NON_SEQ_FILL_OUTPUTS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 3
#define LUT_RUNTIME_CONVERT_OUTPUTS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 4
#define LUT_RUNTIME_BACKWARD_NON_SEQ_BACKPROP_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 5
#define LUT_RUNTIME_BACKWARD_NON_SEQ_PROPAGATE_DETECTORS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 6
#define LUT_RUNTIME_BACKWARD_NON_SEQ_GATHER_GRADIENTS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 7
#define LUT_RUNTIME_BACKWARD_NON_SEQ_PROPAGATE_DETECTORS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 8
#define LUT_RUNTIME_BACKWARD_NON_SEQ_GATHER_GRADIENTS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 9
#define LUT_RUNTIME_FORWARD_SEQ_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 10
#define LUT_RUNTIME_FORWARD_SEQ_CHECK_DETECTORS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 11
#define LUT_RUNTIME_FORWARD_SEQ_CHECK_POSITIONAL_EMBEDDINGS_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 12
#define LUT_RUNTIME_FORWARD_SEQ_FILL_OUTPUTS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 13
#define LUT_RUNTIME_FORWARD_SEQ_FILL_OUTPUTS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 14
#define LUT_RUNTIME_BACKWARD_SEQ_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 15
#define LUT_RUNTIME_BACKWARD_SEQ_PROPAGATE_THROUGH_DETECTORS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 16
#define LUT_RUNTIME_BACKWARD_SEQ_PROPAGATE_THROUGH_DETECTORS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 17
#define LUT_RUNTIME_BACKWARD_SEQ_GATHER_W_GRADIENTS_SPARSE_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 18
#define LUT_RUNTIME_BACKWARD_SEQ_GATHER_W_GRADIENTS_FC_PROFILER_OP N_CONNECTIONS_MANAGER_PROFILER_OPS + 19
#define N_LUT_PROFILER_OPS (N_CONNECTIONS_MANAGER_PROFILER_OPS + 20)
#endif

static_assert(sizeof(EXTERNAL_REAL_DT) == 4, "this lut implementation works only with float32 weights");

typedef struct alignas(8) {
    NeuronIndex_t anchor1_id;
    NeuronIndex_t anchor2_id;
} AnchorsPair;
static_assert((sizeof(AnchorsPair) % 8) == 0, "check sizeof(AnchorsPair)");

#define AnchorsPairs(id, storage_data) ((AnchorsPair *)(storage_data + id))
